### PR TITLE
Testing how to work with spanish translation

### PR DESCRIPTION
**Pull request by deimidis**
First file, just a test to see if we can work in this way

### CODE REVIEW

**Comment by stefanbohacek** [comment]
@deimidis Thank you, this looks good! Could you please just change the language code to `es-es`?

**Comment by deimidis** [comment]
Do you think I have to follow es-ES or just es-es it's ok?

**Comment by stefanbohacek** [comment]
`es-es` will be okay, the language codes are turned to lowercase here https://github.com/jointhefediverse-net/jointhefediverse.net/blob/main/public/js/modules/language-switcher.js#L9.

Thank you!

**Comment by deimidis** [comment]
Great, made the changes. I think I can't approve it, right. Also, I need to change some other files with es-es, I will do it later

**Comment by stefanbohacek** [comment]
Looks good, thank you!

**Pull request merged**
