### PR TITLE
Create es.json files

### PR DESCRIPTION
**Pull request by barredo**
Here's a translation to Spanish. I made it as neutral as possible, but it is possible it would need to be classified as Spanish from Spain (es_es)

### CODE REVIEW

**Comment by stefanbohacek** [comment]
Thank you, really appreciate your help!

Let me ping @j3j5 and @deimidis, who have also been working on Spanish translation.

Please note that the translated text goes inside the `translations` directory as per the instructions here: https://github.com/jointhefediverse-net/jointhefediverse.net#translation

**Comment by deimidis** [comment]
Hi @barredo I started to translate it too, but in the data files. I will take your full translation as a base too, so we can discuss it if we find something to change

**Comment by stefanbohacek** [comment]
@barredo Hi, could you please let me know how you'd like to be credited for your work?

https://github.com/jointhefediverse-net/jointhefediverse.net/blob/main/translations/es-es.json#L7

**Comment by barredo** [comment]
> @barredo Hi, could you please let me know how you'd like to be credited for your work?
> 
> https://github.com/jointhefediverse-net/jointhefediverse.net/blob/main/translations/es-es.json#L7

Ohhh, I appreciate it. Just "Alex Barredo" or my masto profile? https://mastodon.social/@Barredo -- Thank you

**Comment by stefanbohacek** [comment]
No problem, and thank you!

https://jointhefediverse.net/about

**Pull request closed without merging**
