### PR TITLE
Update home.json

### PR DESCRIPTION
**Pull request by anauta**
Corrected some typos and minor errors

### CODE REVIEW

**Comment by anauta** [comment]
(I'm new to pull requests so tell me if I make any blunder or breach etiquette)

**Comment by stefanbohacek** [comment]
@anauta This is perfect, thank you!

Please let me know if/how you'd like to be credited on https://jointhefediverse.net/about.

**Comment by anauta** [comment]
I'll credit myself when credit is deserved, not yet! :)

**Comment by stefanbohacek** [comment]
@anauta I always make sure to credit everyone who contributes, regardless of the scope of their contribution, but this is ultimately your call. Feel free to reconsider!

Either way, again, thank you so much!

**Pull request merged**
